<?php

/**
 * @file
 * Main file for Entity Options module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\entity_options\EntityOptionsItemList;

/**
 * Implements hook_entity_base_field_info().
 */
function entity_options_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'node') {
    return [
      'entity_options' => BaseFieldDefinition::create('entity_options_map')
        ->setLabel(t('Entity Options'))
        ->setTranslatable(TRUE)
        ->setComputed(TRUE)
        ->setCustomStorage(TRUE)
        ->setClass(EntityOptionsItemList::class)
        ->setDisplayOptions('form', [
          'type' => 'entity_options',
          'weight' => 30,
          'region' => 'hidden',
        ])
        ->setDisplayConfigurable('form', TRUE),
    ];
  }
  return [];
}

/**
 * Implements hook_entity_insert().
 */
function entity_options_entity_insert(EntityInterface $entity) {
  \Drupal::service('plugin.manager.entity_options')->updateEntityOptions($entity, 'insert');
}

/**
 * Implements hook_entity_update().
 */
function entity_options_entity_update(EntityInterface $entity) {
  \Drupal::service('plugin.manager.entity_options')->updateEntityOptions($entity, 'insert');
}

/**
 * Implements hook_entity_delete().
 */
function entity_options_entity_delete(EntityInterface $entity) {
  \Drupal::service('plugin.manager.entity_options')->purgeEntityOptions($entity);
}
