<?php

/**
 * @file
 * Install file for mailboxlayer.
 */

use Drupal\webform\Entity\Webform;

/**
 * Implements hook_schema().
 */
function mailboxlayer_schema() {
  $schema['mailboxlayer_log'] = [
    'description' => 'To store the Mailboxlayer response to optimize the usage of the Mailboxlayer API',
    'fields' => [
      'id' => [
        'description' => 'ID',
        'type' => 'serial',
        'not null' => TRUE,
      ],
      'email' => [
        'description' => 'Email ID',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
      'format_valid' => [
        'description' => 'Valid Format',
        'type' => 'int',
        'size' => 'tiny',
        'unsigned' => TRUE,
        'not null' => FALSE,
      ],
      'mx_found' => [
        'description' => 'MX Found',
        'type' => 'int',
        'size' => 'tiny',
        'unsigned' => TRUE,
        'not null' => FALSE,
      ],
      'smtp_check' => [
        'description' => 'SMTP Check',
        'type' => 'int',
        'size' => 'tiny',
        'unsigned' => TRUE,
        'not null' => FALSE,
      ],
      'catch_all' => [
        'description' => 'Catch All',
        'type' => 'int',
        'size' => 'tiny',
        'unsigned' => TRUE,
        'not null' => FALSE,
      ],
      'role' => [
        'description' => 'Role',
        'type' => 'int',
        'size' => 'tiny',
        'unsigned' => TRUE,
        'not null' => FALSE,
      ],
      'disposable' => [
        'description' => 'Disposable',
        'type' => 'int',
        'size' => 'tiny',
        'unsigned' => TRUE,
        'not null' => FALSE,
      ],
      'free' => [
        'description' => 'Free',
        'type' => 'int',
        'size' => 'tiny',
        'unsigned' => TRUE,
        'not null' => FALSE,
      ],
      'score' => [
        'description' => 'Score',
        'type' => 'float',
        'size' => 'tiny',
        'not null' => FALSE,
      ],
      'created' => [
        'description' => 'Created',
        'type' => 'int',
        'not null' => FALSE,
        'default' => NULL,
      ],
    ],
    'primary key' => [
      'id',
    ],
  ];

  return $schema;
}

/**
 * Implements hook_uninstall().
 */
function mailboxlayer_uninstall() {
  // Getting module configuration.
  $config = \Drupal::service('config.factory')->getEditable('mailboxlayer.settings');
  // Webform lists.
  $webform_list = $config->get('enabled_webforms');
  foreach ($webform_list as $key => $value) {
    $webform = Webform::load($key);
    $webformElements = $webform->getElementsDecoded();

    // Iterating throught the fields to identify the email field key.
    foreach ($webformElements as $key => $value) {
      if ($value['#type'] == 'email') {
        // Removing the mailboxlayer property from the email fields.
        unset($webformElements[$key]['#mailboxlayer_enabled']);
      }
    }
    $webform->setElements($webformElements);
    $webform->save();
  }
}
