<?php

/**
 * @file
 * Provides a better queue API.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\advancedqueue\Hook\AdvancedqueueHooks;

/**
 * Implements hook_cron().
 */
#[LegacyHook]
function advancedqueue_cron() {
  \Drupal::service(AdvancedqueueHooks::class)->cron();
}

/**
 * Implements hook_theme().
 */
#[LegacyHook]
function advancedqueue_theme() {
  return \Drupal::service(AdvancedqueueHooks::class)->theme();
}
