<?php

/**
 * @file
 * PHPMailer SMTP installation functions.
 */

/**
 * Add SMTP timeout setting.
 */
function phpmailer_smtp_update_8001() {
  \Drupal::configFactory()->getEditable('phpmailer_smtp.settings')
    ->set('smtp_timeout', 30)
    ->save(TRUE);
}

/**
 * Add Authentication type setting.
 */
function phpmailer_smtp_update_8002() {
  \Drupal::configFactory()->getEditable('phpmailer_smtp.settings')
    ->set('smtp_authentication_type', 'basic_auth')
    ->save(TRUE);
}

/**
 * Add Email format setting.
 */
function phpmailer_smtp_update_8003() {
  \Drupal::configFactory()->getEditable('phpmailer_smtp.format')
    ->set('format', 'plain_text')
    ->save(TRUE);
}

/**
 * Add Send all email as HTML setting.
 */
function phpmailer_smtp_update_8004() {
  \Drupal::configFactory()->getEditable('phpmailer_smtp.format')
    ->set('force_html', 0)
    ->save(TRUE);
}
