<?php

/**
 * @file
 * Contains universal_file_utils_download.module.
 */

/**
 * Implements hook_module_implements_alter().
 */
function universal_file_utils_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    // Move our hook_file_download() implementation to the start of the list.
    case 'file_download':
      $group = $implementations['universal_file_utils'];
      unset($implementations['universal_file_utils']);
      $implementations = ['universal_file_utils' => $group] + $implementations;
      break;
  }
}

/**
 * Implements hook_file_download().
 */
function universal_file_utils_file_download($uri) {
  if (strpos($uri, '/system/files/') === FALSE) {
    if (strpos($uri, 'private://') === FALSE) {
      return [];
    }
  }
  return \Drupal::service('universal_file_utils.operations')->HookFileDownload($uri);
}

/**
 * Implements hook_file_access().
 */
function universal_file_utils_file_access($entity, $operation, $account) {
  return \Drupal::service('universal_file_utils.operations')->HookFileAccess($entity, $operation, $account);
}
