name: Schema Based Config Forms Media Library Form Element
type: module
description: 'Provides ''media_reference_id'' and ''media_references'' schema types for use with config forms.'
core_version_requirement: ^10 || ^11
package: Config
dependencies:
  - media_library_form_element:media_library_form_element

# Information added by Drupal.org packaging script on 2025-07-11
version: '1.0.0-beta6'
project: 'schema_based_config_forms'
datestamp: 1752271076
