<?php

/**
 * @file
 * Module file for ajax_quiz module.
 */

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\RedirectCommand;
use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\Core\Form\FormStateInterface;
use Drupal\quiz\Form\QuizQuestionAnsweringForm;
use Drupal\quiz\Form\QuizQuestionFeedbackForm;

/**
 * AJAX callback for quiz submission.
 *
 * This must remain procedural as it is referenced by string in #ajax arrays.
 */
function ajax_quiz_navigate_quiz($form, FormStateInterface $form_state) {
  $commands = new AjaxResponse();

  /** @var \Drupal\quiz\Services\QuizSessionInterface $quiz_session */
  $quiz_session = \Drupal::service('quiz.session');

  if (isset($form['#quiz_result'])) {
    $quiz_result = $form['#quiz_result'];
  }
  else {
    $quiz_result = $quiz_session->getTemporaryResult();
  }

  if ($quiz_result) {
    $quiz = $quiz_result->getQuiz();
  }
  else {
    $quiz = FALSE;
  }

  if ($quiz && $quiz_session->getCurrentQuestion($quiz) !== NULL) {
    $question_number = $quiz_session->getCurrentQuestion($quiz);
    if ($form_state->get('feedback')) {
      $question_number--;
    }
  }
  else {
    $question_number = 0;
  }

  $layout = $quiz_result->getLayout();
  if ($quiz_result && isset($layout[$question_number])) {
    $question_node = NULL;

    $question = $layout[$question_number];

    if (!empty($question->qqr_pid)) {
      foreach ($layout as $pquestion) {
        if ($pquestion->qqr_id == $question->qqr_pid) {
          $question_node = $pquestion->getQuizQuestion();
        }
      }
    }
    else {
      $question_node = $question->getQuizQuestion();
    }

    if ($question_node) {
      if ($form_state->get('feedback')) {
        $feedback = \Drupal::formBuilder()
          ->getForm(QuizQuestionFeedbackForm::class, $quiz, $question_number);
        $commands->addCommand(new ReplaceCommand('#ajax-quiz-wrapper', \Drupal::service('renderer')->render($feedback)));
        return $commands;
      }
      else {
        $build_info = $form_state->getBuildInfo();
        $build_info['args'][0] = $question_node;
        $form_state->setBuildInfo($build_info);
        $quiz_result->setQuestion($question_number);

        $questions = [];
        $i = 0;
        foreach ($quiz_result->getLayout() as $idx => $question) {
          if (empty($question->qqr_pid)) {
            $questions[$idx] = ++$i;
          }
        }

        $progress = [
          '#theme' => 'quiz_progress',
          '#total' => count($questions),
          '#current' => $question_number,
        ];

        $commands->addCommand(new ReplaceCommand("#quiz-progress", \Drupal::service('renderer')
          ->render($progress)));

        if ($form['#form_id'] == 'quiz_report_form') {
          return \Drupal::formBuilder()
            ->getForm(QuizQuestionAnsweringForm::class, $quiz, $question_node, $quiz_result->id());
        }
        else {
          $form_state->setRebuild();
          $form = \Drupal::formBuilder()
            ->rebuildForm($form['#form_id'], $form_state, $form);
          $form['#action'] = '/system/ajax';
          return $form;
        }
      }
    }
  }
  elseif ($quiz_result) {
    $commands->addCommand(new RedirectCommand('/quiz/' . $quiz_result->getQuiz()->id() . '/result/' . $quiz_result->id()));
  }
  else {
    $commands->addCommand(new RedirectCommand('/quiz/' . $quiz->id()));
  }

  return $commands;
}
