<?php

/**
 * @file
 * Primary module hooks for AI Media Image module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\media\Entity\MediaType;

/**
 * Implements hook_help().
 */
function ai_media_image_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.ai_media_image') {
    $readme_content = file_get_contents(dirname(__FILE__) . '/README.md');
    if (\Drupal::moduleHandler()->moduleExists('markdown')) {
      // Use the Markdown filter to render the README.
      $filter_manager = \Drupal::service('plugin.manager.filter');
      $markdown_config = \Drupal::configFactory()->get('markdown.settings')->getRawData();
      $markdown_settings = ['settings' => $markdown_config];
      $filter = $filter_manager->createInstance('markdown', $markdown_settings);

      return $filter->process($readme_content, 'en');
    }
    else {
      return '<pre>' . $readme_content . '</pre>';
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function ai_media_image_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'media_image_add_form':
    case 'media_library_add_form_upload':
    case 'media_library_add_form_dropzonejs':
      // Only show the AI option if the user has the right permission.
      $current_user = \Drupal::currentUser();
      if ($current_user->hasPermission('generate image with ai')) {
        if ($form_state->get('media_library_state')) {
          $media_type = $form_state->get('media_library_state')->get('media_library_selected_type');
        }
        else {
          $media_type = 'image';
        }
        if ($media_type == 'image') {
          $form['image_source'] = [
            '#type' => 'select',
            '#title' => t('Image Source'),
            '#weight' => -1,
            '#options' => [
              'upload' => t('Upload Image'),
              'ai' => t('Generate Image with AI'),
            ],
            '#default_value' => 'upload',
            '#states' => [
              'invisible' => [
                'li.media-library-add-form__media' => [
                  '!value' => '',
                ],
              ],
            ],
          ];
          $image_field_name = _ai_media_image_get_image_field_name('image');
          if ($form_id == 'media_image_add_form' && $image_field_name) {
            $form[$image_field_name]['#states'] = [
              'invisible' => [
                'select[name="image_source"]' => [
                  'value' => 'ai',
                ],
              ],
            ];
          }
          if (str_contains($form_id, 'media_library_add_form') && !empty($form['container'])) {
            $form['container']['#states'] = [
              'invisible' => [
                'select[name="image_source"]' => [
                  'value' => 'ai',
                ],
              ],
            ];
          }

          $form = array_merge($form, \Drupal::service('ai_media_image.add_form')->buildInputElement($form, $form_state));

          $form['ai_media_image']['generator_container']['prompt']['#states'] = [
            'required' => [
              'select[name="image_source"]' => [
                'value' => 'ai',
              ],
            ],
          ];

          if ($image_field_name) {
            $form[$image_field_name]['widget'][0]['#required'] = FALSE;
          }

          $form['#validate'][] = 'ai_media_image_add_form_validate';
        }
      }

      break;
  }
}

/**
 * Media add form validate handler.
 */
function ai_media_image_add_form_validate($form, $form_state) {
  $form_state->clearErrors();
  $values = $form_state->getValues();
  $image_field_name = _ai_media_image_get_image_field_name('image');

  if ($form_state->getTriggeringElement()['#name'] != 'addAiImage') {
    // If saving the image.
    switch ($values['image_source']) {
      case 'upload':
        if (!empty($values['media'][0]['target_id'])) {
          $media = \Drupal::entityTypeManager()->getStorage('media')->load($values['media'][0]['target_id']);
          if ($media && $image_field_name && $media->get($image_field_name)->isEmpty()) {
            $form_state->setError($form[$image_field_name]['widget'][0], t('Image field is required.'));
          }
        }
        break;

      case 'ai':
        if (empty($form_state->get('image_data'))) {
          $form_state->setError($form['ai_media_image']['generator_container']['image_preview'], t('Please generate an image.'));
        }
        elseif (empty($values['alt_text'])) {
          $form_state->setError($form['ai_media_image']['generator_container']['image_preview']['alt_text'], t('Please provide alternative text.'));
        }
        else {
          $form_state->setSubmitHandlers(['ai_media_image_add_form_submit']);
        }
        break;
    }
  }
  else {
    // If clicked on the Generate Image button.
    $form_state->setValue('upload', [
      'fids' => [],
    ]);
    if ($values['image_source'] == 'ai' && empty($values['prompt'])) {
      $form_state->setError($form['ai_media_image']['generator_container']['prompt'], t('Please provide a prompt.'));
    }
  }
}

/**
 * Media add form submit handler.
 */
function ai_media_image_add_form_submit($form, $form_state) {
  \Drupal::service('ai_media_image.add_form')->submitForm($form, $form_state);
}

/**
 * Check if default provider is chosen and model is selected.
 */
function _ai_media_image_check_default_provider_and_model() {
  $ai_config = \Drupal::service('config.factory')->get('ai.settings');
  $default_providers = $ai_config->get('default_providers') ?? [];
  if (
    !isset($default_providers['text_to_image']['provider_id']) && !isset($default_providers['text_to_image']['model_id'])
    ||
    $default_providers['text_to_image']['provider_id'] == ""
    || $default_providers['text_to_image']['model_id'] == ''
  ) {
    \Drupal::messenger()->addMessage(t('Please set a default text_to_image provider & model in the <a href="/admin/config/ai/settings">AI module settings</a>.'), 'error', FALSE);
  }
}

/**
 * Helper function to get the image field name for a given media type.
 */
function _ai_media_image_get_image_field_name($media_type_id) {
  $media_type = MediaType::load($media_type_id);
  if ($media_type) {
    return $media_type->getSource()->getSourceFieldDefinition($media_type)->getName();
  }
  return NULL;
}
