default_providers:
  chat:
    provider_id: openai
    model_id: gpt-5
  chat_with_complex_json:
    provider_id: openai
    model_id: gpt-4
  chat_with_image_vision:
    provider_id: openai
    model_id: gpt-5
  chat_with_structured_response:
    provider_id: openai
    model_id: gpt-5
  chat_with_tools:
    provider_id: openai
    model_id: gpt-5
  embeddings:
    provider_id: openai
    model_id: text-embedding-3-small
  moderation:
    provider_id: openai
    model_id: omni-moderation-latest
  speech_to_text:
    provider_id: openai
    model_id: whisper-1
  text_to_image:
    provider_id: openai
    model_id: dall-e-3
  text_to_speech:
    provider_id: openai
    model_id: tts-1
  translate_text:
    provider_id: chat_translation
    model_id: gpt-3.5-turbo
default_vdb_provider: ''
