_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: bartik
defaults:
  sender: symfony_mailer
  formatter: symfony_mailer
modules:
  mail_box_management:
    none:
      sender: phpmailer_smtp
      formatter: phpmailer_smtp
