_core:
  default_config_hash: GL7ygb-sUJwtEtFI_8Z3Qd8mBJpr2h5lTL6DIOQKs98
smtp_host: ssl0.ovh.net
smtp_hostbackup: smtp.mail.ovh.net
smtp_port: 587
smtp_protocol: tls
smtp_username: dpalicepeio@drupbuilder.org
smtp_password: dpRoger_1928
smtp_hide_password: true
smtp_authentication_type: basic_auth
smtp_fromname: ''
smtp_always_replyto: false
smtp_keepalive: true
smtp_debug: 1
smtp_debug_log: true
phpmailer_smtp_test: ''
smtp_ssl_verify_peer: false
smtp_ssl_verify_peer_name: false
smtp_ssl_allow_self_signed: true
smtp_envelope_sender_option: site_mail
smtp_envelope_sender: ''
smtp_ehlo_host: ''
smtp_timeout: 30
