<?php

/**
 * @file
 * Schema Based Config Forms Entity Reference module file.
 */

/**
 * Implements hook_schema_config_form_element_info_alter().
 */
function schema_based_config_forms_entity_reference_schema_config_form_element_info_alter(array &$definitions): void {
  if (isset($definitions['entity_reference_id'])) {
    $definitions['entity_reference_id']['types'][] = 'entity_reference_id';
    $definitions['entity_reference_id']['types'][] = 'entity_reference_id_int';
  }
}
