<?php

/**
 * @file
 * Install, update and uninstall functions for the group module.
 */

/**
 * Implements hook_update_last_removed().
 */
function group_update_last_removed() {
  return 10305;
}

/**
 * Drop deprecated keys from config entities.
 */
function group_update_11400() {
  $config_factory = \Drupal::configFactory();

  // Drop creator_wizard key from group types.
  foreach ($config_factory->listAll('group.type.') as $config_name) {
    $group_type = $config_factory->getEditable($config_name);
    $group_type->clear('creator_wizard');
    $group_type->save();
  }

  // Drop use_creation_wizard key from group relationship types.
  foreach ($config_factory->listAll('group.relationship_type.') as $config_name) {
    $relationship_type = $config_factory->getEditable($config_name);

    $plugin_config = $relationship_type->get('plugin_config');
    unset($plugin_config['use_creation_wizard']);
    $relationship_type->set('plugin_config', $plugin_config);

    $relationship_type->save();
  }
}

/**
 * Rename "content_plugin" to "relation_type" on group relationship types.
 */
function group_update_11401() {
  $config_factory = \Drupal::configFactory();
  foreach ($config_factory->listAll('group.relationship_type.') as $config_name) {
    $relationship_type = $config_factory->getEditable($config_name);

    $plugin_id = $relationship_type->get('content_plugin');
    $relationship_type->clear('content_plugin');
    $relationship_type->set('relation_type', $plugin_id);

    $relationship_type->save();
  }
}
